#!/usr/bin/perl -W

#use MLDBM qw(DB_File);
use Fcntl;
use NDBM_File;

if ($#ARGV < 1) {
  print "Error: arguments missing.\n\n";
  &usage;
  exit -1;
}


my $parfile = shift;
my $row_num = shift;

my $dbfilename = "$parfile";

#tie(%param_rows, 'MLDBM', $dbfilename, O_RDONLY, 0666 );
tie(%param_rows, 'NDBM_File', $dbfilename, O_RDONLY, 0666 ) or
  die "Cannot access the parameter database $dbfilename\n";

# read parameter row
print $param_rows{$row_num};

untie $param_rows;

sub usage {
  print "Usage: $0 parameter_file row_num\n\n" .
    "Reads a row from the parameter database using a hash-based \n" .
      "access without searching all rows. Run create_perlhash_param_db \n" .
	"to initialize the database file from a text-based parameter file.\n\n";
}
